---
# Based on https://docs.ansible.com/ansible/latest
# /collections/ansible/builtin/apt_module.html#examples
- name: >-
    UPGRADE operation on ALL of the nodes
    (*WARNING* includes reboot if needed, including localhost)
  hosts: all
  become: true
  tasks:
    - name: Update all repos and perfrom upgrade to latest versions
      register: upgrade_status
      apt:
        # * upgrade is expecting a string value. In addition to yes and no you can use dist, full, or safe
        upgrade: 'yes'
        update_cache: true
        cache_valid_time: 3600
        # force_apt_get: true
    - name: Show upgrade results
      debug: msg="{{ upgrade_status.stdout_lines }}"
      when: "upgrade_status.stdout.find('0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.') == -1 \
      and upgrade_status.stdout.find('No packages will be installed, upgraded, or removed.') == -1"

    - name: Check if a reboot is needed
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_checksum=no

    - name: Reboot the box if needed (like kernel updated)
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 10
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists
